name: nutty
version: 0.9
summary: A Network Information Utility
description: A simple application to provide essential information on network related aspects. Nutty provides basic network information, internet usage and speed and monitors devices connected to the network.
confinement: strict

apps:
  nutty:
    command: nutty
    plugs: [x11, unity7, network]

parts:
    granite:
        plugin: cmake
        source: lp:granite/0.4
        source-type: bzr
        configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
        build-packages:
            - build-essential
            - valac
        stage-packages:
            - valac-0.30-vapi
    nutty:
        plugin: cmake
        source: lp:nutty
        source-type: bzr
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
        after: [granite]
        build-packages:
            - build-essential
            - valac
            - intltool
            - libnotify-dev
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
        stage-packages:
            - gnome-keyring
            - gobject-introspection
            - libgdk-pixbuf2.0-0
            - libgee-0.8-2
            - libgtk-3-0
            - libnotify4
            - libpango-1.0-0
            - libpangocairo-1.0-0
            - net-tools
            - nmap
            - traceroute
            - vnstat
            - nethogs
            - gksu
            - curl
            - wireless-tools



